<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
text= """경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n
남 말하기는 식은 죽 먹기\n
말 많은 집은 장의 맛도 쓰다\n
말이 말을 만든다\n
쑥떡같이 말 알아라"""

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
t = Tokenizer()
t.fit_on_texts([text])
#리스트 형태
print(t)
encoded = t.texts_to_sequences([text])[0]
#텍스트 안의 단어들을 숫자의 시퀀스의 형태로 변환

In [3]:
#케라스 토크나이저의 정수 인코딩은 인덱스가 1부터 시작하지만 
#케라스 원-핫 인코딩에서 배열의 인덱스가 0부터 시작하기 때문에 배열의 크기를 실제 단어 집합의 크기보다 +1로 생성해야함으로 미리 +1선언
vocab_size = len(t.word_index) + 1

print("단어 집합의 크기: %d" % vocab_size)

단어 집합의 크기: 27


In [4]:
print(t.word_index)

{'말이': 1, '말': 2, '경마장에': 3, '있는': 4, '뛰고': 5, '있다': 6, '그의': 7, '법이다': 8, '가는': 9, '고와야': 10, '오는': 11, '곱다': 12, '남': 13, '말하기는': 14, '식은': 15, '죽': 16, '먹기': 17, '많은': 18, '집은': 19, '장의': 20, '맛도': 21, '쓰다': 22, '말을': 23, '만든다': 24, '쑥떡같이': 25, '알아라': 26}


In [5]:
sequences = list()

for line in text.split('\n'):
    print([line])
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

['경마장에 있는 말이 뛰고 있다']
['']
['그의 말이 법이다']
['']
['가는 말이 고와야 오는 말이 곱다']
['']
['남 말하기는 식은 죽 먹기']
['']
['말 많은 집은 장의 맛도 쓰다']
['']
['말이 말을 만든다']
['']
['쑥떡같이 말 알아라']


In [6]:
print(sequences)
print(max(len(I) for I in sequences))

[[3, 4], [3, 4, 1], [3, 4, 1, 5], [3, 4, 1, 5, 6], [7, 1], [7, 1, 8], [9, 1], [9, 1, 10], [9, 1, 10, 11], [9, 1, 10, 11, 1], [9, 1, 10, 11, 1, 12], [13, 14], [13, 14, 15], [13, 14, 15, 16], [13, 14, 15, 16, 17], [2, 18], [2, 18, 19], [2, 18, 19, 20], [2, 18, 19, 20, 21], [2, 18, 19, 20, 21, 22], [1, 23], [1, 23, 24], [25, 2], [25, 2, 26]]
6


In [7]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
sequences = pad_sequences(sequences, maxlen=6, padding='pre')


In [8]:
print(sequences)

[[ 0  0  0  0  3  4]
 [ 0  0  0  3  4  1]
 [ 0  0  3  4  1  5]
 [ 0  3  4  1  5  6]
 [ 0  0  0  0  7  1]
 [ 0  0  0  7  1  8]
 [ 0  0  0  0  9  1]
 [ 0  0  0  9  1 10]
 [ 0  0  9  1 10 11]
 [ 0  9  1 10 11  1]
 [ 9  1 10 11  1 12]
 [ 0  0  0  0 13 14]
 [ 0  0  0 13 14 15]
 [ 0  0 13 14 15 16]
 [ 0 13 14 15 16 17]
 [ 0  0  0  0  2 18]
 [ 0  0  0  2 18 19]
 [ 0  0  2 18 19 20]
 [ 0  2 18 19 20 21]
 [ 2 18 19 20 21 22]
 [ 0  0  0  0  1 23]
 [ 0  0  0  1 23 24]
 [ 0  0  0  0 25  2]
 [ 0  0  0 25  2 26]]


In [9]:
import numpy as np
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:, -1]

print(X)

[[ 0  0  0  0  3]
 [ 0  0  0  3  4]
 [ 0  0  3  4  1]
 [ 0  3  4  1  5]
 [ 0  0  0  0  7]
 [ 0  0  0  7  1]
 [ 0  0  0  0  9]
 [ 0  0  0  9  1]
 [ 0  0  9  1 10]
 [ 0  9  1 10 11]
 [ 9  1 10 11  1]
 [ 0  0  0  0 13]
 [ 0  0  0 13 14]
 [ 0  0 13 14 15]
 [ 0 13 14 15 16]
 [ 0  0  0  0  2]
 [ 0  0  0  2 18]
 [ 0  0  2 18 19]
 [ 0  2 18 19 20]
 [ 2 18 19 20 21]
 [ 0  0  0  0  1]
 [ 0  0  0  1 23]
 [ 0  0  0  0 25]
 [ 0  0  0 25  2]]


In [10]:
print(y)

[ 4  1  5  6  1  8  1 10 11  1 12 14 15 16 17 18 19 20 21 22 23 24  2 26]


In [11]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=vocab_size)
print(y)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0

In [12]:
from tensorflow.keras.layers  import Embedding, Dense, SimpleRNN
from tensorflow.keras.models import Sequential

model = Sequential()

model.add(Embedding(vocab_size, 10, input_length=5))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 3.2911 - accuracy: 0.0417
Epoch 2/200
1/1 - 0s - loss: 3.2830 - accuracy: 0.0833
Epoch 3/200
1/1 - 0s - loss: 3.2749 - accuracy: 0.0833
Epoch 4/200
1/1 - 0s - loss: 3.2669 - accuracy: 0.0833
Epoch 5/200
1/1 - 0s - loss: 3.2588 - accuracy: 0.0833
Epoch 6/200
1/1 - 0s - loss: 3.2507 - accuracy: 0.1667
Epoch 7/200
1/1 - 0s - loss: 3.2424 - accuracy: 0.2083
Epoch 8/200
1/1 - 0s - loss: 3.2340 - accuracy: 0.2500
Epoch 9/200
1/1 - 0s - loss: 3.2254 - accuracy: 0.2500
Epoch 10/200
1/1 - 0s - loss: 3.2164 - accuracy: 0.2500
Epoch 11/200
1/1 - 0s - loss: 3.2071 - accuracy: 0.2917
Epoch 12/200
1/1 - 0s - loss: 3.1975 - accuracy: 0.2917
Epoch 13/200
1/1 - 0s - loss: 3.1875 - accuracy: 0.2917
Epoch 14/200
1/1 - 0s - loss: 3.1771 - accuracy: 0.2917
Epoch 15/200
1/1 - 0s - loss: 3.1663 - accuracy: 0.2917
Epoch 16/200
1/1 - 0s - loss: 3.1550 - accuracy: 0.2500
Epoch 17/200
1/1 - 0s - loss: 3.1433 - accuracy: 0.2500
Epoch 18/200
1/1 - 0s - loss: 3.1312 - accuracy: 0.2500
E

Epoch 147/200
1/1 - 0s - loss: 0.9199 - accuracy: 0.8750
Epoch 148/200
1/1 - 0s - loss: 0.9067 - accuracy: 0.8750
Epoch 149/200
1/1 - 0s - loss: 0.8937 - accuracy: 0.8750
Epoch 150/200
1/1 - 0s - loss: 0.8809 - accuracy: 0.8750
Epoch 151/200
1/1 - 0s - loss: 0.8682 - accuracy: 0.8750
Epoch 152/200
1/1 - 0s - loss: 0.8557 - accuracy: 0.9167
Epoch 153/200
1/1 - 0s - loss: 0.8434 - accuracy: 0.9167
Epoch 154/200
1/1 - 0s - loss: 0.8313 - accuracy: 0.9167
Epoch 155/200
1/1 - 0s - loss: 0.8193 - accuracy: 0.9167
Epoch 156/200
1/1 - 0s - loss: 0.8075 - accuracy: 0.9167
Epoch 157/200
1/1 - 0s - loss: 0.7959 - accuracy: 0.9583
Epoch 158/200
1/1 - 0s - loss: 0.7845 - accuracy: 0.9583
Epoch 159/200
1/1 - 0s - loss: 0.7732 - accuracy: 0.9583
Epoch 160/200
1/1 - 0s - loss: 0.7621 - accuracy: 0.9583
Epoch 161/200
1/1 - 0s - loss: 0.7512 - accuracy: 0.9583
Epoch 162/200
1/1 - 0s - loss: 0.7404 - accuracy: 0.9583
Epoch 163/200
1/1 - 0s - loss: 0.7298 - accuracy: 0.9583
Epoch 164/200
1/1 - 0s - loss: 

In [13]:
def sentence_generation(model, t, current_word, n):
    init_word = current_word
    sentence= ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        result = model.predict_classes(encoded, verbose=0)
        
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' '+ word
    
    sentence = init_word + sentence
    return sentence

In [15]:
print(sentence_generation(model, t, '경마장에', 4))

C:\Users\User\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


경마장에 있는 말이 뛰고 있다


In [18]:
print(sentence_generation(model, t, '집은', 5))

집은 말이 고와야 오는 말이 곱다
